### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by denull** [williewillus/BugfixMod#6]
Link to this mod's page (http://williewillus.wordpress.com/BugfixMod) is broken. There's no prebuilt version available?

Also, any reason why this mod isn't available on CurseForge?

**Comment by williewillus** [comment]
this mod is unsupported. it's the first mod I ever wrote, and is a hacky mess no one should really be using. 
additionally, in 1.12 literally all of the bugs this mod fixes have been fixed in vanilla or forge itself.
sorry about that

**Comment by williewillus** [comment]
I really don't think the bugs this fixes are that game-breaking, but whatever. Just follow the [LICENSE](https://github.com/williewillus/BugfixMod/blob/master/LICENSE)

**Comment by deNULL** [comment]
Okay, thank you. The most annoying bug was the boat desynchronisation issue. That's the reason I was searching for a patch to fix it.

Another thing that is bothering me (and other players on my server) is inability to sleep in a bed placed above y=128, but that fix should be easy to add.
